const mexico = document.getElementById("mexico")
const colombia = document.getElementById("colombia")
const argentina = document.getElementById("argentina")
const españa = document.getElementById("spain")
const brazil = document.getElementById("brazil")
const russia = document.getElementById("russia")
const australia = document.getElementById("australia")
const usa = document.getElementById("usa")
const peru = document.getElementById("peru")
const uruguay = document.getElementById("uruguay")
const chile = document.getElementById("chile")
const ecuador = document.getElementById("ecuador")
const bolivia = document.getElementById("bolivia")
const venezuela = document.getElementById("venezuela")
const paraguay = document.getElementById("paraguay")
const guyane = document.getElementById("guyane")
const guyana = document.getElementById("guyana")
const suriname = document.getElementById("suriname")
const canada = document.getElementById("canada")
const alaska = document.getElementById("alaska")
const alaska2 = document.getElementById("alaska-westcopy")
const greenland = document.getElementById("greenland")
const spain = document.getElementById("spain")
const germany = document.getElementById("germany")
const france = document.getElementById("france")
const poland = document.getElementById("poland")
const portugal = document.getElementById("portugal")
const itali = document.getElementById("italy")
const United = document.getElementById("mongolia")
const Croatia = document.getElementById("croatia")
const Belgium = document.getElementById("belgium")
const ukranie = document.getElementById("ukraine")
const Netherlands = document.getElementById("netherlands")
const Turkey = document.getElementById("turkey")
const finland = document.getElementById("finland")
const sweden = document.getElementById("sweden")
const antarctica = document.getElementById("east antarctica")
const peninsula = document.getElementById("antarctic peninsula")
const chukotka = document.getElementById("chukotka")
const algeria = document.getElementById("algeria")
const Egypt = document.getElementById("egypt")
const Cameroon = document.getElementById("cameroon")
const Nigeria = document.getElementById("nigeria")
const Morocco = document.getElementById("morocco")
const Denmark = document.getElementById("denmark")
const Dominican = document.getElementById("domincan republic")
const Jamaica = document.getElementById("jamaica")
const baffin = document.getElementById("baffin")
const libya = document.getElementById("libya")
const drc = document.getElementById("drc")
const angola = document.getElementById("angola")
const south = document.getElementById("south africa")
const mali = document.getElementById("mali")
const sudan = document.getElementById("sudan")
const niger = document.getElementById("niger")
const chad = document.getElementById("chad")
const mauretania = document.getElementById("mauretania")
const ethiopia = document.getElementById("ethiopia")
const tanzania = document.getElementById("tanzania")
const namibia = document.getElementById("namibia")
const mozambique = document.getElementById("mozambique")
const centrafrique = document.getElementById("centrafrique")
const kenya = document.getElementById("kenya")
const botswana = document.getElementById("botswana")
const somalia = document.getElementById("somalia")
const ivoire = document.getElementById("ivoire")
const zambia = document.getElementById("zambia")
const gabon = document.getElementById("gabon")
const congo = document.getElementById("congo")
const southsudan = document.getElementById("south_sudan")
const senegal = document.getElementById("senegal")
const guinee = document.getElementById("guinee")
const zimbabwe = document.getElementById("zimbabwe")
const ghana = document.getElementById("ghana")
const burkina = document.getElementById("burkina")
const uganda = document.getElementById("uganda")
const tunisia = document.getElementById("tunisia")
const liberia = document.getElementById("liberia")
const benin = document.getElementById("benin")
const malawi = document.getElementById("malawi")
const somaliland = document.getElementById("somaliland")
const eritrea = document.getElementById("eritrea")
const sierra = document.getElementById("sierra leone")
const lesotho = document.getElementById("lesotho")
const china = document.getElementById("china")
const india = document.getElementById("india")
const iran = document.getElementById("iran")
const south_korea = document.getElementById("south korea")
const Pakistan = document.getElementById("pakistan")
const afghanistan = document.getElementById("afghanistan")
const turkmenistan = document.getElementById("turkmenistan")
const uzbekistan = document.getElementById("uzbekistan")
const kazakhstan = document.getElementById("kazakhstan")
const kirgizstan = document.getElementById("kirgizstan")
const tajikistan = document.getElementById("tajikistan")
const romania = document.getElementById("romania")
const belarus = document.getElementById("belarus")
const ellesmere = document.getElementById("ellesmere")
const victoria = document.getElementById("victoria")
const banks = document.getElementById("banks")
const honduras = document.getElementById("honduras")
const guatemala = document.getElementById("guatemala")
const nicaragua = document.getElementById("nicaragua")
const costarica = document.getElementById("costa rica")
const panama = document.getElementById("panama")
const saudi = document.getElementById("saudi")
const oman = document.getElementById("oman")
const yemen = document.getElementById("yemen")
const norway = document.getElementById("norway")
const iraq = document.getElementById("iraq")
const newzelanS = document.getElementById("new zealand south island")
const newzelandN = document.getElementById("new zealand north island")
const papua_new_guinea = document.getElementById("papua new guinea")
const irian_jaya = document.getElementById("irian jaya")
const burma = document.getElementById("burma")
const laos = document.getElementById("laos")
const north_korea = document.getElementById("north korea")
const thailand = document.getElementById("thailand")
const vietnam = document.getElementById("vietnam")
const nepal = document.getElementById("nepal")
const bangladesh = document.getElementById("bangladesh")
const syria = document.getElementById("syria")
const serbia = document.getElementById("serbia")
const lithuania = document.getElementById("lithuania")
const devon = document.getElementById("devon")
const eglinton = document.getElementById("eglinton")
const axel_heiberg = document.getElementById("axel heiberg")
const tasmania = document.getElementById("tasmania")
const new_britain = document.getElementById("new britain")
const kalimantan = document.getElementById("kalimantan")
const east_malaysia = document.getElementById("east malaysia")
const sulawesi = document.getElementById("sulawesi")
const cambodia = document.getElementById("cambodia")
const jordan = document.getElementById("jordan")
const bulgaria = document.getElementById("bulgaria")
const czech = document.getElementById("czech")
const hungary = document.getElementById("hungary")
const georgia = document.getElementById("georgia")
const southhampton = document.getElementById("southhampton")
const prince_of_wales = document.getElementById("prince of wales")
const prescott = document.getElementById("prescott")
const prince_patrick = document.getElementById("prince patrick")
const ellef_ringnes = document.getElementById("ellef ringnes")
const bathurst = document.getElementById("bathurst")
const azerbaijan = document.getElementById("azerbaijan")
const austria = document.getElementById("austria")
const estonia = document.getElementById("estonia")
const path302 = document.getElementById("path302")
const greece = document.getElementById("greece")
const armenia = document.getElementById("armenia")
const emirates = document.getElementById("emirates")
const slovakia = document.getElementById("slovakia")
const switzerland= document.getElementById("switzerland")
const bosnia = document.getElementById("bosnia")




colombia.addEventListener('click', selections)
function selections() {
    
    suriname.setAttribute("fill","red")
    guyana.setAttribute("fill","red")
    guyane.setAttribute("fill","red")
    paraguay.setAttribute("fill","red")
    venezuela.setAttribute("fill","red")
    bolivia.setAttribute("fill","red")
    ecuador.setAttribute("fill","red")
    chile.setAttribute("fill","red") 
    uruguay.setAttribute("fill","red")  
    peru.setAttribute("fill","red")
    brazil.setAttribute("fill","red")
    argentina.setAttribute("fill" ,"red")
    colombia.setAttribute("fill" ,"red")
}


usa.addEventListener('click', selecc)
function selecc() {
    bathurst.setAttribute("fill","yellow")
    ellef_ringnes.setAttribute("fill","yellow")
    prince_patrick.setAttribute("fill","yellow")
    prince_of_wales.setAttribute("fill","yellow")
    southhampton.setAttribute("fill","yellow")
    axel_heiberg.setAttribute("fill","yellow")
    eglinton.setAttribute("fill","yellow")
    devon.setAttribute("fill","yellow")
    panama.setAttribute("fill","yellow")
    costarica.setAttribute("fill","yellow")
    nicaragua.setAttribute("fill","yellow")
    banks.setAttribute("fill","yellow")
    victoria.setAttribute("fill","yellow")
    ellesmere.setAttribute("fill","yellow")
    baffin.setAttribute("fill","yellow")
    Dominican.setAttribute("fill","yellow")
    Jamaica.setAttribute("fill","yellow")
    chukotka.setAttribute("fill","yellow")
    greenland.setAttribute("fill","yellow")
    alaska2.setAttribute("fill","yellow")
    mexico.setAttribute("fill","yellow")
    canada.setAttribute("fill","yellow")
    usa.setAttribute("fill","yellow")
    honduras.setAttribute("fill","yellow")
    guatemala.setAttribute("fill","yellow")
    prescott.setAttribute("fill","yellow")
}


spain.addEventListener('click', selection23)
function selection23() {
    bosnia.setAttribute("fill","blue")
    switzerland.setAttribute("fill","blue")
    slovakia.setAttribute("fill","blue")
    emirates.setAttribute("fill","blue")
    path302.setAttribute("fill","blue")
    estonia.setAttribute("fill","blue")
    austria.setAttribute("fill","blue")
    azerbaijan.setAttribute("fill","blue")
    georgia.setAttribute("fill","blue")
    hungary.setAttribute("fill","blue")
    czech.setAttribute("fill","blue")
    bulgaria.setAttribute("fill","blue")
    jordan.setAttribute("fill","blue")
    lithuania.setAttribute("fill","blue")
    serbia.setAttribute("fill","blue")
    syria.setAttribute("fill","blue")
    norway.setAttribute("fill","blue")
    oman.setAttribute("fill","blue")
    yemen.setAttribute("fill","blue")
    saudi.setAttribute("fill","blue")
    belarus.setAttribute("fill","blue")
    romania.setAttribute("fill","blue")
    Denmark.setAttribute("fill","blue")
    sweden.setAttribute("fill","blue")
    finland.setAttribute("fill","blue")
    Turkey.setAttribute("fill","blue")
    russia.setAttribute("fill","blue")
    Netherlands.setAttribute("fill","blue")
    ukranie.setAttribute("fill","blue")
    Belgium.setAttribute("fill","blue")
    Croatia.setAttribute("fill","blue")
    United.setAttribute("fill","blue")
    itali.setAttribute("fill","blue")
    portugal.setAttribute("fill","blue")
    poland.setAttribute("fill","blue")
    france.setAttribute("fill","blue")
    germany.setAttribute("fill","blue")
    spain.setAttribute("fill","blue")
    greece.setAttribute("fill","blue")
    armenia.setAttribute("fill","blue")
}


antarctica.addEventListener('click', selectionan)
function selectionan() {
    peninsula.setAttribute("fill","green")
    antarctica.setAttribute("fill","green")
}

australia.addEventListener('click', selectaust)
function selectaust() {
    sulawesi.setAttribute("fill","pink")
    east_malaysia.setAttribute("fill","pink")
    kalimantan.setAttribute("fill","pink")
    new_britain.setAttribute("fill","pink")
    tasmania.setAttribute("fill","pink")
    irian_jaya.setAttribute("fill","pink")
    papua_new_guinea.setAttribute("fill","pink")
    newzelandN.setAttribute("fill","pink")
    newzelanS.setAttribute("fill","pink")
    australia.setAttribute("fill","pink")
}


algeria.addEventListener('click',slectafri)
function slectafri() {
    lesotho.setAttribute("fill","purple")
    sierra.setAttribute("fill","purple")
    eritrea.setAttribute("fill","purple")
    somaliland.setAttribute("fill","purple")
    malawi.setAttribute("fill","purple")
    benin.setAttribute("fill","purple")
    liberia.setAttribute("fill","purple")
    tunisia.setAttribute("fill","purple")
    uganda.setAttribute("fill","purple")
    burkina.setAttribute("fill","purple")
    ghana.setAttribute("fill","purple")
    zimbabwe.setAttribute("fill","purple")
    senegal.setAttribute("fill","purple")
    guinee.setAttribute("fill","purple")
    southsudan.setAttribute("fill","purple")
    gabon.setAttribute("fill","purple")
    congo.setAttribute("fill","purple")
    zambia.setAttribute("fill","purple")
    ivoire.setAttribute("fill","purple")
    somalia.setAttribute("fill","purple")
    botswana.setAttribute("fill","purple")
    kenya.setAttribute("fill","purple")
    centrafrique.setAttribute("fill","purple")
    mozambique.setAttribute("fill","purple")
    namibia.setAttribute("fill","purple")
    tanzania.setAttribute("fill","purple")
    ethiopia.setAttribute("fill","purple")
    mauretania.setAttribute("fill","purple")
    chad.setAttribute("fill","purple")
    niger.setAttribute("fill","purple")
    sudan.setAttribute("fill","purple")
    mali.setAttribute("fill","purple")
    south.setAttribute("fill","purple")
    angola.setAttribute("fill","purple")
    drc.setAttribute("fill","purple")
    libya.setAttribute("fill" ,"purple")
    Morocco.setAttribute("fill","purple")
    Nigeria.setAttribute("fill","purple")
    Cameroon.setAttribute("fill","purple")  
    algeria.setAttribute("fill","purple")
    Egypt.setAttribute("fill","purple")
}

china.addEventListener('click', selectedf)
function selectedf() {

    cambodia.setAttribute("fill","orange")
    bangladesh.setAttribute("fill","orange")
    vietnam.setAttribute("fill","orange")
    thailand.setAttribute("fill","orange")
    north_korea.setAttribute("fill","orange")
    laos.setAttribute("fill","orange")
    burma.setAttribute("fill","orange")
    iraq.setAttribute("fill","orange")
    tajikistan.setAttribute("fill","orange")
    kirgizstan.setAttribute("fill","orange")
    kazakhstan.setAttribute("fill","orange")
    uzbekistan.setAttribute("fill","orange")
    turkmenistan.setAttribute("fill","orange")
    afghanistan.setAttribute("fill","orange")
    Pakistan.setAttribute("fill","orange")
    south_korea.setAttribute("fill","orange")
    iran.setAttribute("fill","orange")
    india.setAttribute("fill","orange")
    china.setAttribute("fill","orange")
    nepal.setAttribute("fill","orange")
}