const mexico = document.getElementById("mexico")
const colombia = document.getElementById("colombia")
const argentina = document.getElementById("argentina")
const españa = document.getElementById("spain")
const brazil = document.getElementById("brazil")
const russia = document.getElementById("russia")
const australia = document.getElementById("australia")
const usa = document.getElementById("usa")
const peru = document.getElementById("peru")
const uruguay = document.getElementById("uruguay")
const chile = document.getElementById("chile")
const ecuador = document.getElementById("ecuador")
const bolivia = document.getElementById("bolivia")
const venezuela = document.getElementById("venezuela")
const paraguay = document.getElementById("paraguay")
const guyane = document.getElementById("guyane")
const guyana = document.getElementById("guyana")
const suriname = document.getElementById("suriname")
const canada = document.getElementById("canada")
const alaska = document.getElementById("alaska")
const alaska2 = document.getElementById("alaska-westcopy")
const greenland = document.getElementById("greenland")
const spain = document.getElementById("spain")
const germany = document.getElementById("germany")
const france = document.getElementById("france")
const poland = document.getElementById("poland")
const portugal = document.getElementById("portugal")
const itali = document.getElementById("italy")
const United = document.getElementById("mongolia")
const Croatia = document.getElementById("croatia")
const Belgium = document.getElementById("belgium")
const ukranie = document.getElementById("ukraine")
const Netherlands = document.getElementById("netherlands")
const Turkey = document.getElementById("turkey")
const finland = document.getElementById("finland")
const sweden = document.getElementById("sweden")
const antarctica = document.getElementById("east antarctica")
const peninsula = document.getElementById("antarctic peninsula")
const chukotka = document.getElementById("chukotka")
const algeria = document.getElementById("algeria")
const Egypt = document.getElementById("egypt")
const Cameroon = document.getElementById("cameroon")
const Nigeria = document.getElementById("nigeria")
const Morocco = document.getElementById("morocco")
const Denmark = document.getElementById("denmark")
const Dominican = document.getElementById("domincan republic")
const Jamaica = document.getElementById("jamaica")
const baffin = document.getElementById("baffin")
const libya = document.getElementById("libya")
const drc = document.getElementById("drc")
const angola = document.getElementById("angola")
const south = document.getElementById("south africa")
const mali = document.getElementById("mali")
const sudan = document.getElementById("sudan")
const niger = document.getElementById("niger")
const chad = document.getElementById("chad")
const mauretania = document.getElementById("mauretania")
const ethiopia = document.getElementById("ethiopia")


colombia.addEventListener('click', selections)
function selections() {
    suriname.setAttribute("fill","red")
    guyana.setAttribute("fill","red")
    guyane.setAttribute("fill","red")
    paraguay.setAttribute("fill","red")
    venezuela.setAttribute("fill","red")
    bolivia.setAttribute("fill","red")
    ecuador.setAttribute("fill","red")
    chile.setAttribute("fill","red") 
    uruguay.setAttribute("fill","red")  
    peru.setAttribute("fill","red")
    brazil.setAttribute("fill","red")
    argentina.setAttribute("fill" ,"red")
    colombia.setAttribute("fill" ,"red")
}


usa.addEventListener('click', selecc)
function selecc() {
    baffin.setAttribute("fill","yellow")
    Dominican.setAttribute("fill","yellow")
    Jamaica.setAttribute("fill","yellow")
    chukotka.setAttribute("fill","yellow")
    greenland.setAttribute("fill","yellow")
    alaska2.setAttribute("fill","yellow")
    mexico.setAttribute("fill","yellow")
    canada.setAttribute("fill","yellow")
    usa.setAttribute("fill","yellow")
    
}


spain.addEventListener('click', selection23)
function selection23() {
    Denmark.setAttribute("fill","blue")
    sweden.setAttribute("fill","blue")
    finland.setAttribute("fill","blue")
    Turkey.setAttribute("fill","blue")
    russia.setAttribute("fill","blue")
    Netherlands.setAttribute("fill","blue")
    ukranie.setAttribute("fill","blue")
    Belgium.setAttribute("fill","blue")
    Croatia.setAttribute("fill","blue")
    United.setAttribute("fill","blue")
    itali.setAttribute("fill","blue")
    portugal.setAttribute("fill","blue")
    poland.setAttribute("fill","blue")
    france.setAttribute("fill","blue")
    germany.setAttribute("fill","blue")
    spain.setAttribute("fill","blue")
}


antarctica.addEventListener('click', selectionan)
function selectionan() {
    peninsula.setAttribute("fill","green")
    antarctica.setAttribute("fill","green")
}

australia.addEventListener('click', selectaust)
function selectaust() {
    australia.setAttribute("fill","pink")
}


algeria.addEventListener('click',slectafri)
function slectafri() {
    ethiopia.setAttribute("fill","purple")
    mauretania.setAttribute("fill","purple")
    chad.setAttribute("fill","purple")
    niger.setAttribute("fill","purple")
    sudan.setAttribute("fill","purple")
    mali.setAttribute("fill","purple")
    south.setAttribute("fill","purple")
    angola.setAttribute("fill","purple")
    drc.setAttribute("fill","purple")
    libya.setAttribute("fill" ,"purple")
    Morocco.setAttribute("fill","purple")
    Nigeria.setAttribute("fill","purple")
    Cameroon.setAttribute("fill","purple")  
    algeria.setAttribute("fill","purple")
    Egypt.setAttribute("fill","purple")
}